name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    name: test
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Set up Go 1.24.2
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: Run Tests
      run: make test
