# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: ci-test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  test:
    name: test
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.24.2
      uses: actions/setup-go@v4
      with:
        go-version: '1.24.2'

    - name: check out code into the Go module directory
    - uses: actions/checkout@v4

    - name: Test
      run: make test
